apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webapp-canary
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webapp
      rollout: canary
  template:
    metadata:
      labels:
        app: webapp
        rollout: canary
    spec:
      containers:
      - name: webapp
        image: emon110852/webapp:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 3
  strategy:
    canary:
      steps:
      - setWeight: 10               # send 10% traffic to new pods
      - pause: {duration: 30s}      # wait to observe
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 100
